site_name: Yifan's Notes
site_description: Yifan's Notes
site_url: http://notes.yifanli.me

theme:
  name: 'material'

pages:
    - Home: 'index.md'
    - Books and Documents: 'books.md'
    - Progress Bar: 'progress.md'
    - Topics: 'topics.md'
    - ISDM:
        - 'Index': 'isdm/index.md'
        - 'Chapter 1 About This Manual': 'isdm/chapter1.md'
        - 'Chapter 2 Intel64 And IA-32 Architectures': 'isdm/chapter2.md'
    - DP:
        - 'Index': 'dp/index.md'
        - 'Motivation': 'dp/motivation.md'

